part1

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np
import geocoder
import folium
from sklearn.cluster import KMeans
from pandas.io.json import json_normalize
from geopy.geocoders import Nominatim
import matplotlib.cm as cm
import matplotlib.colors as colors

In [4]:
#request for data from urlk
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
#parse data with BeautifulSoup
soup = BeautifulSoup(res.content,'html.parser')
#find data from table
table = soup.find_all('table')[0]
#read data with pandas from table
d = pd.read_html(str(table))[0]
#convert to dataframe
df = pd.DataFrame(d)
#define column
df.columns = ['Postalcode','Brought','Neighbourhood']
#remove row which are 'Not assigned' in Brought column
df1 = df[df.Brought != 'Not assigned']
#Grouping Neighbourhood where Postalcode are same
df2 = df1.groupby(['Postalcode','Brought'])['Neighbourhood'].apply(', '.join).reset_index()
#Replce Neighbourhood's value with Brought's value where are Neighbourhood is 'Not assigned'
df2['Neighbourhood'] = np.where((df2['Neighbourhood'] == 'Not assigned'),df2['Brought'],df2['Neighbourhood'])
#showing sample output
df2.head()

  Postalcode      Brought                           Neighbourhood
0        M1B  Scarborough                          Rouge, Malvern
1        M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

In [ ]:
#read Latitude,Latitude data locally
import csv
ll_data = pd.read_csv(Geospatial_Coordinates.csv)
#convert to dataframe
df3 = pd.DataFrame(ll_data)
#define column
df3.columns = ['Postalcode','Latitude','Longitude']
#showing sample output
df3.head()

In [5]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [6]:
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(res.content,'html.parser')
table = soup.find_all('table')[0]
d = pd.read_html(str(table))[0]
df = pd.DataFrame(d)
df.columns = ['Postcode','Brought','Neighbourhood']
df.head()

  Postcode           Brought     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [7]:

df.shape

(288, 3)

In [8]:
df1 = df[df.Brought != 'Not assigned']
df1.shape

(211, 3)

In [11]:
df2 = df1.groupby(['Postcode','Brought'])['Neighbourhood'].apply(', '.join).reset_index()
df2.head(12)

   Postcode      Brought                                      Neighbourhood
0       M1B  Scarborough                                     Rouge, Malvern
1       M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2       M1E  Scarborough                  Guildwood, Morningside, West Hill
3       M1G  Scarborough                                             Woburn
4       M1H  Scarborough                                          Cedarbrae
5       M1J  Scarborough                                Scarborough Village
6       M1K  Scarborough        East Birchmount Park, Ionview, Kennedy Park
7       M1L  Scarborough                    Clairlea, Golden Mile, Oakridge
8       M1M  Scarborough    Cliffcrest, Cliffside, Scarborough Village West
9       M1N  Scarborough                        Birch Cliff, Cliffside West
10      M1P  Scarborough  Dorset Park, Scarborough Town Centre, Wexford ...
11      M1R  Scarborough                                  Maryvale, Wexford

In [12]:
df2['Neighbourhood'] = np.where((df2['Neighbourhood'] == 'Not assigned'),df2['Brought'],df2['Neighbourhood'])
df2

,Postcode,Brought,Neighbourhood
0,M1B,Scarborough,"Rouge, Malvern"
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
5,M1J,Scarborough,Scarborough Village
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park"
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge"
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West"
9,M1N,Scarborough,"Birch Cliff, Cliffside West"
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ..."
11,M1R,Scarborough,"Maryvale, Wexford"
12,M1S,Scarborough,Agincourt
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter"
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St..."
15,M1W,Scarborough,L'Amoreaux West
16,M1X,Scarborough,Upper Rouge
17,M2H,North York,Hillcrest Village
18,M2J,North York,"Fairview, Henry Farm, Oriole"
19,M2K,North York,Bayview Village
20,M2L,North York,"Silver Hills, York Mills"
21,M2M,North York,"Newtonbrook, Willowdale"
22,M2N,North York,Willowdale South
23,M2P,North York,York Mills West
24,M2R,North York,Willowdale West
25,M3A,North York,Parkwoods
26,M3B,North York,Don Mills North
27,M3C,North York,"Flemingdon Park, Don Mills South"
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights"
29,M3J,North York,"Northwood Park, York University"
...,...,...,...
73,M6C,York,Humewood-Cedarvale
74,M6E,York,Caledonia-Fairbanks
75,M6G,Downtown Toronto,Christie
76,M6H,West Toronto,"Dovercourt Village, Dufferin"
77,M6J,West Toronto,"Little Portugal, Trinity"
78,M6K,West Toronto,"Brockton, Exhibition Place, Parkdale Village"
79,M6L,North York,"Downsview, North Park, Upwood Park"
80,M6M,York,"Del Ray, Keelesdale, Mount Dennis, Silverthorn"
81,M6N,York,"The Junction North, Runnymede"
82,M6P,West Toronto,"High Park, The Junction South"
83,M6R,West Toronto,"Parkdale, Roncesvalles"
84,M6S,West Toronto,"Runnymede, Swansea"
85,M7A,Queen's Park,Queen's Park
86,M7R,Mississauga,Canada Post Gateway Processing Centre
87,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
88,M8V,Etobicoke,"Humber Bay Shores, Mimico South, New Toronto"
89,M8W,Etobicoke,"Alderwood, Long Branch"
90,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
91,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So..."
92,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen..."
93,M9A,Etobicoke,Islington Avenue
94,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ..."
95,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol..."
96,M9L,North York,Humber Summit
97,M9M,North York,"Emery, Humberlea"
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv..."
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ..."
102,M9W,Etobicoke,Northwest

In [13]:

df2.shape

(103, 3)

part2

In [14]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np
#import geocoder

In [15]:
#request for data from urlk
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
#parse data with BeautifulSoup
soup = BeautifulSoup(res.content,'html.parser')
#find data from table
table = soup.find_all('table')[0]
#read data with pandas from table
d = pd.read_html(str(table))[0]
#convert to dataframe
df = pd.DataFrame(d)
#define column
df.columns = ['Postalcode','Brought','Neighbourhood']
#remove row which are 'Not assigned' in Brought column
df1 = df[df.Brought != 'Not assigned']
#Grouping Neighbourhood where Postalcode are same
df2 = df1.groupby(['Postalcode','Brought'])['Neighbourhood'].apply(', '.join).reset_index()
#Replce Neighbourhood's value with Brought's value where are Neighbourhood is 'Not assigned'
df2['Neighbourhood'] = np.where((df2['Neighbourhood'] == 'Not assigned'),df2['Brought'],df2['Neighbourhood'])
#showing sample output
df2.head()

  Postalcode      Brought                           Neighbourhood
0        M1B  Scarborough                          Rouge, Malvern
1        M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

In [13]:
#merge tow dataframe with Postalcode
df4 = pd.merge(df2, df3,on='Postalcode', how='outer')
#showing sample output
df4.head(12)

,Postalcode,Brought,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849

part3

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np
import geocoder as geo
import folium as fm
from sklearn.cluster import KMeans
from pandas.io.json import json_normalize
from geopy.geocoders import Nominatim
import matplotlib.cm as cm
import matplotlib.colors as colors

In [3]:
#request for data from urlk
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
#parse data with BeautifulSoup
soup = BeautifulSoup(res.content,'html.parser')
#find data from table
table = soup.find_all('table')[0]
#read data with pandas from table
d = pd.read_html(str(table))[0]
#convert to dataframe
df = pd.DataFrame(d)
#define column
df.columns = ['Postalcode','Brought','Neighbourhood']
#remove row which are 'Not assigned' in Brought column
df1 = df[df.Brought != 'Not assigned']
#Grouping Neighbourhood where Postalcode are same
df2 = df1.groupby(['Postalcode','Brought'])['Neighbourhood'].apply(', '.join).reset_index()
#Replce Neighbourhood's value with Brought's value where are Neighbourhood is 'Not assigned'
df2['Neighbourhood'] = np.where((df2['Neighbourhood'] == 'Not assigned'),df2['Brought'],df2['Neighbourhood'])

#showing sample output
df2.head()

  Postalcode      Brought                           Neighbourhood
0        M1B  Scarborough                          Rouge, Malvern
1        M1C  Scarborough  Highland Creek, Rouge Hill, Port Union
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

In [5]:
#read Latitude,Latitude data locally
import numpy as np
import pandas as pd
import matplotlib as plt

ll_data=pd.read_csv ("http://cocl.us/Geospatial_data")
#convert to dataframe
df3 = pd.DataFrame(ll_data)
#define column
df3.columns = ['Postalcode','Latitude','Longitude']
#showing sample output
df3.head()

  Postalcode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [10]:
#merge tow dataframe with Postalcode
df4 = pd.merge(df2, df3,on='Postalcode', how='outer')
#showing sample output
df4.head(12)

,Postalcode,Brought,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849

In [ ]:
address = 'Toronto, Ontario'
geolocator = Nominatim(user_agent="to_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto, Ontario are {}, {}.'.format(latitude, longitude))

In [ ]:
# create map of Toronto using latitude and longitude values
map_toronto = folium.Map(location=[latitude,longitude], zoom_start=12)
# add markers to map
for lat, lng, borough, neighborhood in zip(df4['Latitude'], df4['Longitude'], df4['Brought'], df4['Neighbourhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
    
map_toronto

In [17]:
df4.Brought.unique()

array(['Scarborough', 'North York', 'East York', 'East Toronto',
       'Central Toronto', 'Downtown Toronto', 'York', 'West Toronto',
       "Queen's Park", 'Mississauga', 'Etobicoke'], dtype=object)

In [18]:
scarborough_data = df4[df4['Brought'] == 'Scarborough'].reset_index(drop=True)
scarborough_data.head()

,Postalcode,Brought,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

In [ ]:
scarborough_address = 'Scarborough, Toronto'

scarborough_geolocator = Nominatim(user_agent="st_explorer")
scarborough_location = scarborough_geolocator.geocode(address)
scarborough_latitude = scarborough_location.latitude
scarborough_longitude = scarborough_location.longitude
print('The geograpical coordinate of Scarborough are {}, {}.'.format(scarborough_latitude, scarborough_longitude))

In [ ]:
# create map of Scarborough using latitude and longitude values
map_scarborough = folium.Map(location=[scarborough_latitude, scarborough_longitude], zoom_start=11)

# add markers to map
for lat, lng, label in zip(scarborough_data['Latitude'], scarborough_data['Longitude'],scarborough_data['Neighbourhood']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_scarborough)  
    
map_scarborough

In [21]:
CLIENT_ID = 'kjjhjghd567kjhjhgfd9887ghgd' 
CLIENT_SECRET = 'bjhhgfgdkjkhghgf456777674nbvvc' 
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: kjjhjghd567kjhjhgfd9887ghgd
CLIENT_SECRET:bjhhgfgdkjkhghgf456777674nbvvc

In [22]:
scarborough_data.loc[0, 'Neighbourhood']

'Rouge, Malvern'

In [23]:
#Get the neighborhood's latitude and longitude values.
neighborhood_latitude = scarborough_data.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = scarborough_data.loc[0, 'Longitude'] # neighborhood longitude value

neighborhood_name = scarborough_data.loc[0, 'Neighbourhood'] # neighborhood name

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name, 
                                                               neighborhood_latitude, 
                                                               neighborhood_longitude))

Latitude and longitude values of Rouge, Malvern are 43.806686299999996, -79.19435340000001.

In [24]:
# #### Now, let's get the top 3 venues that are in Rouge, Malvern within a radius of 500 meters.
LIMIT = 3
radius = 500
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url

'https://api.foursquare.com/v2/venues/explore?&client_id=kjjhjghd567kjhjhgfd9887ghgd&client_secret=bjhhgfgdkjkhghgf456777674nbvvc&v=20180605&ll=43.806686299999996,-79.19435340000001&radius=500&limit=3'

In [25]:
results = requests.get(url).json()
results

{'meta': {'code': 400,
  'errorType': 'invalid_auth',
  'errorDetail': 'Missing access credentials. See https://developer.foursquare.com/docs/api/configuration/authentication for details.',
  'requestId': '5dac354e446ea60039746c8a'},
 'response': {}}

In [26]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [ ]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues.head()

In [37]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [ ]:
scarborough_venues = getNearbyVenues(names=scarborough_data['Neighbourhood'],
                                   latitudes=scarborough_data['Latitude'],
                                   longitudes=scarborough_data['Longitude']
                                  )

In [ ]:
print(scarborough_venues.shape)
scarborough_venues.head()

In [ ]:
scarborough_venues.groupby('Neighborhood').count()

In [ ]:
print('There are {} uniques categories.'.format(len(scarborough_venues['Venue Category'].unique())))

In [ ]:
# one hot encoding
scarborough_onehot = pd.get_dummies(scarborough_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
scarborough_onehot['Neighborhood'] = scarborough_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [scarborough_onehot.columns[-1]] + list(scarborough_onehot.columns[:-1])
scarborough_onehot = scarborough_onehot[fixed_columns]

scarborough_onehot.head()

In [ ]:
scarborough_onehot.shape

In [ ]:
scarborough_grouped = scarborough_onehot.groupby('Neighborhood').mean().reset_index()
scarborough_grouped.head()

In [ ]:
scarborough_grouped.shape

In [ ]:
num_top_venues = 5

for hood in scarborough_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = scarborough_grouped[scarborough_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

In [47]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [ ]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = scarborough_grouped['Neighborhood']

for ind in np.arange(scarborough_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(scarborough_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

In [ ]:
# set number of clusters
kclusters = 5

scarborough_grouped_clustering = scarborough_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(scarborough_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

In [ ]:
scarborough_merged = scarborough_data
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)
# merge scarborough_grouped with scarborough_data to add latitude/longitude for each neighborhood
scarborough_merged = scarborough_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighbourhood')

#replace NAN to 0 
scarborough_merged['Cluster Labels'] = scarborough_merged['Cluster Labels'].replace(np.nan, 0)
#scarborough_merged.head() # check the last columns!
scarborough_merged.head()

In [ ]:
# create map
map_clusters = folium.Map(location=[scarborough_latitude, scarborough_longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(scarborough_merged['Latitude'], scarborough_merged['Longitude'], scarborough_merged['Neighbourhood'],scarborough_merged['Cluster Labels'].astype(int)):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters